version: "3.9"

services:
  api:
    build: .
    container_name: paper-translator-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - APP_ENV=dev
      - APP_REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - paper-data:/data
    depends_on:
      - redis

  worker:
    build: .
    container_name: paper-translator-worker
    command: celery -A app.infra.jobs.celery_app worker --loglevel=info
    environment:
      - APP_ENV=dev
      - APP_REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/code
      - paper-data:/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: paper-translator-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  paper-data:
  redis-data:
